mongo:
  name: jeopardy
  user: app
  host: cluster0.pmnue.mongodb.net
  options: retryWrites=true&w=majority
  timeout: 15
  pass: uZP1QdmKbIP4erWL
vkapp:
  secret: Mvp3kzt1PBNYwoqy00QN
http:
  listenAddr: "0.0.0.0:3021"
mockResponse: n
validateRequest: n
