---
- hosts: web_server
  become: true
  gather_facts: false

  tasks:
    - name: Empty www directory
      file:
        state: absent
        path: /var/www/{{domain_name}}/
    - name: Copy static files
      copy:
        src: ../../goj-frontend/build/
        dest: /var/www/{{domain_name}}/
        owner: root
        group: root
